/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera, PerspectiveCamera } from "@react-three/drei";

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/VDPmop7p9WsgxMtX/scene.splinecode",
  );
  return (
    <>
      <color attach="background" args={["#000000"]} />
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <mesh
            name="Shape 8"
            geometry={nodes["Shape 8"].geometry}
            material={materials.Glass}
            castShadow
            receiveShadow
            position={[0, 0, -10]}
            scale={0.9}
          />
          <mesh
            name="Shape 7"
            geometry={nodes["Shape 7"].geometry}
            material={materials["Gradient Green"]}
            castShadow
            receiveShadow
            position={[0, 0, -70]}
            rotation={[0, 0, Math.PI / 4]}
          />
          <PerspectiveCamera
            name="Camera"
            makeDefault={true}
            far={100000}
            near={70}
            fov={45}
            position={[-199.41, 114.25, 424.45]}
            rotation={[-0.25, -0.36, -0.09]}
            scale={1}
          />
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={0.7}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1000}
            shadow-camera-right={1000}
            shadow-camera-top={1000}
            shadow-camera-bottom={-1000}
            position={[200, 300, 300]}
          />
          <OrthographicCamera
            name="1"
            makeDefault={false}
            far={10000}
            near={-50000}
          />
          <hemisphereLight
            name="Default Ambient Light"
            intensity={0.75}
            color="#eaeaea"
          />
          {/* <directionalLight
            name="Default Light"
            intensity={1}
            position={[0, 0, 100]}
          /> */}
        </scene>
      </group>
    </>
  );
}
