import { Navigation } from "@/components/Navigation";
import { Inter } from "next/font/google";
import { Bebas_Neue } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });
const bebas = Bebas_Neue({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} selection:bg-yellow-400`}>
        <div className="min-h-screen mx-10">
          <Navigation font={bebas} />
          {children}
        </div>

        <Footer />
      </body>
    </html>
  );
}
